# docker-compose.yml
version: '3.2'

services:
    db:
        image: mysql:8.0
        container_name: appsDB
        restart: always
        ports:
            - '6033:3306'
        environment:
            MYSQL_ROOT_PASSWORD: s3web

    app:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - '9090:80'
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 128M